// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxdwsfcuhawxnkbxmqcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZHdzZmN1aGF3eG5rYnhtcWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDY4ODgsImV4cCI6MjA2MDAyMjg4OH0.XNhgWk2Hh9sKt8BNiRPjdkF_Puf-N5-vK9n43uZEoJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);